#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login_check:
  path:     api/login_check
authentication_token:
  path: /authentication_token
  methods: ['POST']
api_platform:
  resource: .
  type: api_platform
  prefix: /api



